// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbyvyzkomtbyihanwmue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ieXZ5emtvbXRieWloYW53bXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNjU4NjYsImV4cCI6MjA1MTY0MTg2Nn0.gIRyFgjI_TD-qDWgm19sE_HjdVDyXmtGc5kuVuEQr1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);